apiVersion: v1
kind: PersistentVolume
metadata:
name: static-pv-hostpath
spec:
capacity:
storage: 15i
accessModes:
- ReadWriteOnce
persistentVolumeReclaimPolicy: Retain
storageClassName: manual
hostPath:
path: /mnt/data/static-pv
type: DirectoryOrCreate

